### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by Inside4ndroid** [zhkrb/cloudflare-scrape-Android#16]
i am using this for https://yesmovies.ai/ but about an hour ago it has started throwing outofbounds error as follows.... :

11-26 19:30:44.988 5331-5351/com.apps.xsousia E/AndroidRuntime: FATAL EXCEPTION: Thread-154
    Process: com.apps.xsousia, PID: 5331
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.htetznaing.xgetter.Cloudflare.getCheckAnswer(Cloudflare.java:176)
        at com.htetznaing.xgetter.Cloudflare.getVisiteCookie(Cloudflare.java:163)
        at com.htetznaing.xgetter.Cloudflare.urlThread(Cloudflare.java:91)
        at com.htetznaing.xgetter.Cloudflare.access$000(Cloudflare.java:30)
        at com.htetznaing.xgetter.Cloudflare$1.run(Cloudflare.java:70)
        at java.lang.Thread.run(Thread.java:818)

EDIT: the error is pointing to this class >>>>

private void getCheckAnswer(String str) throws InterruptedException, IOException {
        String s = regex(str,"name=\"s\" value=\"(.+?)\"").get(0);   //正则取值
        String jschl_vc = regex(str,"name=\"jschl_vc\" value=\"(.+?)\"").get(0);
        String pass = regex(str,"name=\"pass\" value=\"(.+?)\"").get(0);            //
        double jschl_answer = get_answer(str);
        e(String.valueOf(jschl_answer));
        Thread.sleep(3000);
        String req = String.valueOf("https://"+ConnUrl.getHost())+"/cdn-cgi/l/chk_jschl?";
        if (!TextUtils.isEmpty(s)){
            s = Uri.encode(s);
            req+="s="+s+"&";
        }
        req+="jschl_vc="+Uri.encode(jschl_vc)+"&pass="+ Uri.encode(pass)+"&jschl_answer="+jschl_answer;
        e("RedirectUrl",req);
        getRedirectResponse(req);
    }

Any chance of getting it fixed? Thank you

**Comment by zhkrb** [comment]
Its fixed
