### ISSUE TITLE
Error FATAL EXCEPTION

### ISSUE THREAD

**Issue by destroyxx** [zhkrb/cloudflare-scrape-Android#9]
Hello,
I have an error. Do you know why I have this error ? Thx

Website : https://www.gktorrent.tv/torrents/films

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.example.film, PID: 13277
    org.mozilla.javascript.EvaluatorException: missing } after function body (JavaScript#1)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
        at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
        at org.mozilla.javascript.Parser.addError(Parser.java:260)
        at org.mozilla.javascript.Parser.reportError(Parser.java:328)
        at org.mozilla.javascript.Parser.reportError(Parser.java:322)
        at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:493)
        at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:483)
        at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:773)
        at org.mozilla.javascript.Parser.function(Parser.java:916)
        at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3018)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2655)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2553)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2477)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2461)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2442)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2417)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2389)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2378)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2367)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2356)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2345)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2334)
        at org.mozilla.javascript.Parser.condExpr(Parser.java:2298)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2254)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2277)
        at org.mozilla.javascript.Parser.expr(Parser.java:2233)
        at org.mozilla.javascript.Parser.nameOrLabel(Parser.java:1986)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1240)
        at org.mozilla.javascript.Parser.statement(Parser.java:1109)
        at org.mozilla.javascript.Parser.parse(Parser.java:648)
        at org.mozilla.javascript.Parser.parse(Parser.java:583)
        at org.mozilla.javascript.Context.compileImpl(Context.java:2530)
        at org.mozilla.javascript.Context.compileString(Context.java:1515)
        at org.mozilla.javascript.Context.compileString(Context.java:1504)
        at org.mozilla.javascript.Context.evaluateString(Context.java:1259)
        at com.example.film.model.Cloudflare.get_answer(Cloudflare.java:270)
        at com.example.film.model.Cloudflare.getCheckAnswer(Cloudflare.java:168)
        at com.example.film.model.Cloudflare.getVisiteCookie(Cloudflare.java:152)
        at com.example.film.model.Cloudflare.urlThread(Cloudflare.java:90)
        at com.example.film.model.Cloudflare.access$000(Cloudflare.java:28)
        at com.example.film.model.Cloudflare$1.run(Cloudflare.java:68)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by zhkrb** [comment]
try to use the latest version

**Comment by destroyxx** [comment]
I have the last version. I use Rhino.

**Comment by zhkrb** [comment]
I forgot to update this branch. Now is work fine on other website.

I noticed that it changed the anti bot tech. It will return a CAPTCHA challenge page with response code 403

**Comment by destroyxx** [comment]
Ah, thanks. Yes, apparently they added a CAPTCHA.
